
group:
  network_backup_ups_card:
   name: Network Ups Info
   entities:
     - sensor.ups_battery
     - sensor.ups_input_voltage
     - sensor.ups_nominal_input_voltage
     - sensor.ups_load
     - sensor.ups_nominal_output_power
     - sensor.ups_output_voltage
     - sensor.ups_status
     - sensor.ups_time_left
     - sensor.ups_time_on_battery
     - sensor.ups_transfer_count

apcupsd:
  host: 127.0.0.1
  port: 3551

sensor:
  - platform: apcupsd
    name: Network Backup UPS
    resources:
      - bcharge
      - linev
      - loadpct
      - nominv
      - nompower
      - numxfers
      - outputv
      - status
      - timeleft
      - tonbatt

# UPS Automation
automation:
  - alias: 'Notify when UPS goes on battery'
    trigger:
      - platform: state
        entity_id: sensor.ups_status
        from: 'ONLINE'
        to: 'ONBATT'
    action:
      - service: tts.google_say
        data:
          entity_id: media_player.ha_speaker
          message: 'Ups On Battery'
      - service: notify.Pushbullet
        data:
          message: 'We have lost Power'
      - service: notify.chrome_push
        data_template:
          title: "WARNING"
          message: "House has lost power - {{ as_timestamp(now()) | timestamp_custom('%I:%M:%S %p %d%b%Y', true) }}"

  - alias: 'Notify when UPS goes on Main'
    trigger:
      - platform: state
        entity_id: sensor.ups_status
        from: 'ONBATT'
        to: 'ONLINE'
    action:
      - service: tts.google_say
        data:
          entity_id: media_player.ha_speaker
          message: 'Ups On Mains'
      - service: notify.Pushbullet
        data:
          message: 'We have Power'
      - service: notify.chrome_push
        data_template:
          title: "Info"
          message: "House has power - {{ as_timestamp(now()) | timestamp_custom('%I:%M:%S %p %d%b%Y', true) }}"
