homeassistant:
  customize:

    package.node_anchors:
      customize: &customize
        package: 'digital_loggers'

    switch.network_switch_charter_modem:
      friendly_name: Charter Modem
    switch.network_switch_blue_iris_monitor:
      friendly_name: Blue Iris Monitor
    switch.network_switch_blue_iris_pc:
      friendly_name: Blue Iris Pc
    switch.network_switch_asus_router:
      friendly_name: Asus Router
    switch.network_switch_comnet_switches:
      friendly_name: Comnet Switches
    switch.network_switch_kodi_server:
      friendly_name: Kodi Server
    switch.network_switch_home_assistant_server:
      friendly_name: HASS Server
    
group:
  DigitalLoggers_card:
   control: hidden
   name: Network Switch
   entities:
     - switch.network_switch_charter_modem
     - switch.network_switch_asus_router
     - switch.network_switch_blue_iris_monitor
     - switch.network_switch_blue_iris_pc
     - switch.network_switch_comnet_switches
     - switch.network_switch_kodi_server
     - switch.network_switch_home_assistant_server


switch:
  - platform: digitalloggers
    host: 192.168.1.40
    password: !secret digital_loggers_pass
    name: Network Switch
    cycletime: 5
