homeassistant:
  customize:

    package.node_anchors:
      customize: &customize
        package: 'ecobee'

    sensor.set_hold_mode:
      icon: mdi:home
    sensor.hvac_fan:
      haaska_hidden: true
      icon: mdi:fan

##### Config for ecobee
ecobee:
  api_key: !secret ecobee_api_key
  hold_temp: True

######  ecobee3 Mode Sensors
sensor:
  - platform: template
    sensors:
      operating_mode:
        friendly_name: 'Current Operation'
        value_template: "{{ states.climate.thermostat.attributes.operation }}"
  - platform: template
    sensors:
      set_hold_mode:
        friendly_name: 'Current Mode'
        value_template: "{{ states.climate.thermostat.attributes.hold_mode }}"
  - platform: template
    sensors:
      target_temp:
        friendly_name: 'Target Temperature'
        value_template: "{{ states.climate.thermostat.attributes.target_temp_high }}"
  - platform: template
    sensors:
      current_temp:
        friendly_name: 'Current Temperature'
        value_template: "{{ states.climate.thermostat.attributes.current_temperature }}"
  - platform: template
    sensors:
      hvac_fan:
        friendly_name: 'Hvac Fan'
        value_template: "{{ states.climate.thermostat.attributes.fan }}"
