homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'Ha Server Monitor'
    sensor.average_load_15m:
      friendly_name: Cpu load_15m
      icon: mdi:speedometer
    sensor.ha_cpu_temperature:
      friendly_name: Ha Cpu Temperature
      icon: mdi:oil-temperature
    script.ha_dash_usage:
      friendly_name: HA Svr Notify Issue
      icon: mdi:chip
      haaska_hidden: true
    automation.ha_ram_overload:
      friendly_name: HA Svr Automation for Ram
    automation.ha_disk_overload:
      friendly_name: HA Svr Automation for Disk Space
    automation.ha_cpu_overload:
      friendly_name: HA Svr Automation for Cpu Load

group:
  linux_server_card:
   name: Ha Server
   entities:
     - sensor.speedtest_download
     - sensor.speedtest_upload
     - sensor.speedtest_ping
     - sensor.processor_use
     - sensor.load_15m
     - sensor.ha_cpu_temperature
     - sensor.disk_free_home
     - sensor.disk_used_home
     - sensor.disk_use_percent_home
     - sensor.memory_free
     - sensor.memory_use
     - sensor.memory_use_percent
     - sensor.swap_free
     - sensor.swap_use
     - sensor.swap_use_percent
     - sensor.received_enp2s0
     - sensor.sent_enp2s0
     - sensor.packets_received_enp2s0
     - sensor.packets_sent_enp2s0
     - sensor.ipv4_address_enp2s0
     - sensor.last_boot
     - sensor.since_last_boot
     - sensor.myipopendnscom

  ha_server_automations:
   control: hidden
   name: HA Server Alerts
   entities:
    - script.ha_dash_usage
    - input_number.ram_alert_value
    - input_number.disk_alert_value
    - input_number.cpu_alert_value
    - automation.ha_ram_overload
    - automation.ha_disk_overload
    - automation.ha_cpu_overload

sensor:
  - platform: systemmonitor
    resources:
      - type: processor_use
      - type: disk_use_percent
        arg: /home
      - type: disk_use
        arg: /home
      - type: disk_free
        arg: /home
      - type: memory_free
      - type: memory_use_percent
      - type: memory_use
      - type: swap_use_percent
      - type: swap_use
      - type: swap_free
      - type: load_15m
      - type: network_in
        arg: enp2s0
      - type: network_out
        arg: enp2s0
      - type: packets_in
        arg: enp2s0
      - type: packets_out
        arg: enp2s0
      - type: ipv4_address
        arg: enp2s0
      - type: last_boot
      - type: since_last_boot

  - platform: command_line
    name: Ha Cpu Temperature
    command: cat /sys/class/thermal/thermal_zone2/temp
    unit_of_measurement: '°C'
    value_template: '{{ (value|int / 1000 )|round(1) }}'

input_number:
  ram_alert_value:
    name: HA Ram Alert Setpoint
    initial: 85
    min: 0
    max: 100
    step: 5
  disk_alert_value:
    name: HA Disk Alert Setpoint
    initial: 75
    min: 0
    max: 100
    step: 5
  cpu_alert_value:
    name: HA CPU Alert Setpoint
    initial: 80
    min: 0
    max: 100
    step: 5

automation:
############# Ram usuage high on HA server #####################################
  - alias: ha_ram_overload
    trigger:
      - platform: template
        value_template: "{{ states('sensor.memory_use_percent') > states('input_number.ram_alert_value') }}"
    action:
      - service: tts.google_say
        data:
          entity_id: media_player.ha_speaker
          message: 'Ram Usage On HA Server is Excessive'
      - service: notify.Pushbullet
        data:
          message: 'Ram Usage Is Excessive On HA Server'
      - service: notify.chrome_push
        data_template:
          title: "HA Server"
          message: "Ram Usage On HA Server - {{ as_timestamp(now()) | timestamp_custom('%I:%M:%S %p %d%b%Y', true) }}"
          data:
            url: "/home_assistant_group.serversview"
      - service: persistent_notification.create
        data_template:
          title: "HA Server Ram Alert"
          message: "Check HA Server Ram Usage - {{ as_timestamp(now()) | timestamp_custom('%I:%M:%S %p %d%b%Y', true) }}"
          notification_id: "Ram On HA Server"
      - service: script.ha_dash_usage

############# Disk usuage high on HA server #####################################
  - alias: ha_disk_overload
    trigger:
      - platform: template
        value_template: "{{ states('sensor.disk_use_percent_home') > states('input_number.disk_alert_value') }}"
    action:
      - service: tts.google_say
        data:
          entity_id: media_player.ha_speaker
          message: 'Disk Usage On HA Server is Excessive'
      - service: notify.Pushbullet
        data:
          message: 'Disk Usage Is Excessive On HA Server'
      - service: notify.chrome_push
        data_template:
          title: "HA Server"
          message: "Disk Usage On HA Server - {{ as_timestamp(now()) | timestamp_custom('%I:%M:%S %p %d%b%Y', true) }}"
          data:
            url: "/home_assistant_group.serversview"
      - service: persistent_notification.create
        data_template:
          title: "HA Server Disk Alert"
          message: "Check HA Server Disk Usage - {{ as_timestamp(now()) | timestamp_custom('%I:%M:%S %p %d%b%Y', true) }}"
          notification_id: "Disk On HA Server"
      - service: script.ha_dash_usage

####################### High Cpu Usage #########################################
  - alias: ha_cpu_overload
    trigger:
      - platform: template
        value_template: "{{ states('sensor.processor_use')|int > states('input_number.cpu_alert_value')| int }}"
#        for: '00:00:30'
    action:
      - service: tts.google_say
        data:
          entity_id: media_player.ha_speaker
          message: 'Cpu Usage On HA Server is Excessive'
      - service: notify.Pushbullet
        data:
          message: 'Disk Usage Is Excessive On HA Server'
      - service: notify.chrome_push
        data_template:
          title: "HA Server"
          message: "CPU Usage On HA Server - {{ as_timestamp(now()) | timestamp_custom('%I:%M:%S %p %d%b%Y', true) }}"
          data:
            url: "/home_assistant_group.serversview"
      - service: persistent_notification.create
        data_template:
          title: "HA Server CPU Alert"
          message: "Check HA Server CPU Usage - {{ as_timestamp(now()) | timestamp_custom('%I:%M:%S %p %d%b%Y', true) }}"
          notification_id: "CPU On HA Server"
      - service: script.ha_dash_usage

script:
  ha_dash_usage:
    sequence:
      - delay: '00:00:01'
      - service: shell_command.lv_room_dash_wake_up   # in dashboard package
      - service: shell_command.server_alert_dash_lv # in dashboard package
      - delay: '00:05:00'
      - service: shell_command.lv_room_vas   # in dashboard package
