homeassistant:
  customize:

    package.node_anchors:
      customize: &customize
        package: 'Master Bathroom'

    binary_sensor.kids_bathroom_motion:
      friendly_name: Kids Bathroom Motion
      device_class: motion
    switch.wemo_master_bath_fan:
      friendly_name: Master Bath Humidity Fan
      icon: mdi:fan
    switch.wemo_master_bath_heater:
      friendly_name: Master Bath Heat
      icon: mdi:oil-temperature
    switch.getting_dressed:
      friendly_name: Getting Dressed
      icon: mdi:room-service
      haaska_hidden: false
      haaska_name: Getting Dressed
    sensor.bathroom_heater_watts:
      friendly_name: Master Bath Heater Watts
      icon: mdi:power-plug
    automation.master_bath_light_left_on:
      haaska_hidden: true
      hidden: false
      persistence: true
    automation.master_bath_shower_time_off:
      haaska_hidden: true
      hidden: false
      persistence: true
    automation.master_bath_shower_time_on:
      haaska_hidden: true
      hidden: false
      persistence: true
    automation.master_bath_shower_time_warmup_on:
      haaska_hidden: true
      hidden: false
      persistence: true
    automation.master_bath_shower_time_warmup_off:
      haaska_hidden: true
      hidden: false
      persistence: true
    automation.motion_bathroom_home_mode_off:
      haaska_hidden: true
      hidden: false
      persistence: true
    automation.motion_bathroom_home_mode_on:
      haaska_hidden: true
      hidden: false
      persistence: true
    automation.motion_bathroom_evening_mode_on:
      haaska_hidden: true
      hidden: false
      persistence: true
    automation.motion_bathroom_sleep_off:
      haaska_hidden: true
      hidden: false
      persistence: true
    automation.motion_bathroom_sleep_on:
      haaska_hidden: true
      hidden: false
      persistence: true
    automation.master_bath_getting_dressed:
      haaska_hidden: true
      hidden: false
      persistence: true
    sensor.master_bathroom_dimmer_state:
      icon: mdi:remote
      haaska_hidden: true
    sensor.master_bathroom_dimmer_last_update:
      icon: mdi:clock
    sensor.master_bathroom_dimmer_battery:
      icon: mdi:battery
    binary_sensor.bathroom_motion:
      friendly_name: Bathroom Motion
      device_class: motion
    sensor.motion_sensor_bathroom_battery:
      icon: mdi:battery
    sensor.bathroom_temperature:
      friendly_name: Master Bath Temperature
    script.bath_time_on:
      friendly_name: Shower Time Script
      haaska_hidden: true
    script.bath_time_off:
      friendly_name: Finished Shower Script
      haaska_hidden: true
    script.getting_dressed_on:
      friendly_name: Getting Dressed Script On
      haaska_hidden: true
    script.getting_dressed_off:
      friendly_name: Getting Dressed Script Off
      haaska_hidden: true
    # script.shower_time_warmup_on:
    #   friendly_name: Shower Warmup Script On
    #   haaska_hidden: true
    # script.shower_time_warmup_off:
    #   friendly_name: Shower Warmup Sript Off
    #   haaska_hidden: true
    switch.shower_time:
      friendly_name: Shower Time
      haaska_hidden: false
      haaska_name: Shower Time
    # switch.shower_time_warmup:
    #   friendly_name: Shower Time Warmup
    #   haaska_hidden: false
    #   haaska_name: Shower Time
    light.bathroom:
      persistence: false

group:
   master_bath_card:
      control: hidden
      name: Master Bath
      entities:
       - light.bathroom_vanity
       - light.bathroom
       - switch.wemo_master_bath_fan
       - switch.wemo_master_bath_heater
       - switch.getting_dressed
       - sensor.bathroom_heater_watts
       - switch.master_bath
       - binary_sensor.bathroom_motion
       - sensor.bathroom_temperature
       - sensor.motion_sensor_bathroom_battery
       - sensor.master_bathroom_dimmer_state
       - sensor.master_bathroom_dimmer_last_update
       - sensor.master_bathroom_dimmer_battery
       - script.bath_time_on
       - script.bath_time_off
       - script.getting_dressed_on
       - script.getting_dressed_off
#       - script.shower_time_warmup_on
#       - script.shower_time_warmup_off
#       - switch.shower_time_warmup
       - switch.shower_time
       - automation.master_bath_light_left_on
       - automation.master_bath_shower_time_off
       - automation.master_bath_shower_time_on
       - automation.master_bath_shower_time_warmup_on
       - automation.master_bath_shower_time_warmup_off
       - automation.motion_bathroom_home_mode_off
       - automation.motion_bathroom_home_mode_on
       - automation.motion_bathroom_evening_mode_on
       - automation.motion_bathroom_sleep_off
       - automation.motion_bathroom_sleep_on
       - automation.master_bath_getting_dressed

binary_sensor:
  - platform: rest
    resource: !secret MS_rest_36
    value_template: '{{ value_json.state.presence }}'
    scan_interval: 1
    name: bathroom_motion
sensor:
  - platform: rest
    resource: !secret dimmer_rest_33
    value_template: '{{ value_json.state.buttonevent }}'
    scan_interval: 1
    name: 'Master Bathroom Dimmer State'
  - platform: template
    sensors:
      master_bathroom_dimmer_state:
        friendly_name: 'Master Bath Dimmer Last Button Push'
        value_template: >-
                      {% if states('sensor.master_bathroom_dimmer_state_2')[0] == "1" %}
                        On
                      {% elif states('sensor.master_bathroom_dimmer_state_2')[0] == "2" %}
                        Preshower warmup
                      {% elif states('sensor.master_bathroom_dimmer_state_2')[0] == "3" %}
                        Getting Dressed
                      {% elif states('sensor.master_bathroom_dimmer_state_2')[0] == "4" %}
                        Off
                      {% else %}
                        None
                      {% endif %}

  - platform: rest
    resource: !secret dimmer_rest_33
    value_template: '{{ value_json.state.lastupdated }}'
    scan_interval: 10
    name: 'Master Bathroom Dimmer Last Update'

  - platform: template
    sensors:
      master_bathroom_dimmer_last_update:
        friendly_name: 'Master Bath Last Used'
        value_template: >-
          {{ as_timestamp(strptime(states('sensor.master_bathroom_dimmer_last_update_2')[:19], "%Y-%m-%dT%X"))|timestamp_custom("%a, %B %d")}}

  - platform: rest
    resource: !secret dimmer_rest_33
    value_template: '{{ value_json.config.battery }}'
    unit_of_measurement: '%'
    scan_interval: 1800
    name: 'Master Bathroom Dimmer Battery'
  - platform: rest
    resource: !secret MS_rest_35
    value_template: '{{ value_json.state.temperature | float / 100 }}'
    unit_of_measurement: °C
    name: 'Bathroom Temperature'
  - platform: rest
    resource: !secret MS_rest_35
    value_template: '{{ value_json.config.battery }}'
    unit_of_measurement: '%'
    scan_interval: 1800
    name: 'Motion Sensor Bathroom Battery'
  - platform: template
    sensors:
      bathroom_heater_watts:
        value_template: '{{ states.switch.wemo_master_bath_heater.attributes["current_power_w"] | replace(" W", "") | float }}'
        unit_of_measurement: 'W'

automation:
  - alias: Motion Bathroom Home Mode On
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.bathroom_motion
        to: 'on'
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.boolean_home
        state: 'on'
    action:
      - service: light.turn_on
        data:
          entity_id: light.bathroom
          color_temp: 154
          brightness: 255

  - alias: Motion Bathroom Evening Mode On
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.bathroom_motion
        to: 'on'
    condition:
      condition: or
      conditions:
      - condition: state
        entity_id: input_boolean.boolean_early_morning
        state: 'on'
      - condition: state
        entity_id: input_boolean.boolean_movie_time
        state: 'on'
      - condition: state
        entity_id: input_boolean.boolean_evening_time
        state: 'on'
    action:
      - service: light.turn_on
        data:
          entity_id: light.bathroom
          color_temp: 392
          brightness: 74

  - alias: Motion Bathroom Home Mode off
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.bathroom_motion
        to: 'off'
        for:
          minutes: 3
    condition:
      condition: or
      conditions:
      - condition: state
        entity_id: input_boolean.boolean_early_morning
        state: 'on'
      - condition: state
        entity_id: input_boolean.boolean_home
        state: 'on'
      - condition: state
        entity_id: input_boolean.boolean_movie_time
        state: 'on'
      - condition: state
        entity_id: input_boolean.boolean_evening_time
        state: 'on'
      - condition: state
        entity_id: sensor.set_hold_mode
        state: 'home'
    action:
      - service: light.turn_off
        entity_id: light.bathroom

  - alias: Motion Bathroom Sleep On
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.bathroom_motion
        to: 'on'
    condition:
      condition: or
      conditions:
      - condition: state
        entity_id: sensor.set_hold_mode
        state: 'sleep'
      - condition: state
        entity_id: input_boolean.boolean_sleep
        state: 'on'
    action:
      - service: light.turn_on
        data:
          entity_id: light.bathroom
          color_temp: 426
          brightness: 50

  - alias: Motion Bathroom Sleep Off
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.bathroom_motion
        to: 'off'
        for:
          minutes: 5
    condition:
      condition: or
      conditions:
      - condition: state
        entity_id: sensor.set_hold_mode
        state: 'sleep'
      - condition: state
        entity_id: input_boolean.boolean_sleep
        state: 'on'
    action:
      - service: light.turn_off
        entity_id: light.bathroom

  - alias: Master Bath Shower Time Warmup On
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.master_bathroom_dimmer_state
        to: 'Preshower warmup'
    condition:
      condition: and
      conditions:
      - condition: numeric_state
        entity_id: sensor.bathroom_temperature
        below: '72'
    action:
      - service: script.turn_on
        entity_id: script.shower_time_warmup_on

  - alias: Master Bath Shower Time Warmup Off
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: sensor.bathroom_temperature
        above: '74'
    action:
      - service: script.turn_on
        entity_id: script.shower_time_warmup_off
      - service: tts.google_say
        data:
          entity_id: media_player.ha_speaker
          message: 'The Bathroom is warm time for a shower'

  - alias: Master Bath Getting Dressed
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.master_bathroom_dimmer_state
        to: 'Getting Dressed'
    action:
      - service: script.turn_on
        entity_id: script.getting_dressed_on

  - alias: Master Bath Shower Time On
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.master_bathroom_dimmer_state
        to: 'On'
    action:
      - service: script.turn_on
        entity_id: script.bath_time_on

  - alias: Master Bath Shower Time Off
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.master_bathroom_dimmer_state
        to: 'Off'
    action:
      - service: script.turn_on
        entity_id: script.bath_time_off
      - service: script.turn_on
        entity_id: script.shower_time_warmup_off

  - alias: Master Bath light left on
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: light.bathroom_vanity
        to: 'on'
        for:
          hours: 1
          minutes: 00
          seconds: 00
    action:
      - service: automation.turn_on
        entity_id: automation.motion_bathroom_home_mode_on
      - service: automation.turn_on
        entity_id: automation.motion_bathroom_sleep_on
      - service: light.turn_off
        entity_id: light.bathroom_vanity
      - service: light.turn_off
        entity_id: light.bathroom

script:
  bath_time_on:
    sequence:
      - delay: '00:00:01'
      - service: automation.turn_off
        entity_id: automation.motion_bathroom_home_mode_off
      - service: automation.turn_off
        entity_id: automation.motion_bathroom_sleep_off
      - service: automation.turn_off
        entity_id: automation.motion_master_bedroom_motion_off
      - service: light.turn_on
        data:
          entity_id: light.bathroom_vanity
          color_temp: 154
          brightness: 255
      - service: light.turn_on
        data:
          entity_id: light.bathroom
          color_temp: 154
          brightness: 255
      - service: light.turn_on
        data:
          entity_id: light.master_table_lamps
          color_temp: 154
          brightness: 255
      - service: light.turn_on
        data:
          entity_id: light.light_bulb_2
      - service: switch.turn_on
        entity_id: switch.wemo_master_bath_fan


  bath_time_off:
    sequence:
      - delay: '00:00:01'
      - service: automation.turn_on
        entity_id: automation.motion_bathroom_home_mode_off
      - service: automation.turn_on
        entity_id: automation.motion_bathroom_sleep_off
      - service: automation.turn_on
        entity_id: automation.motion_master_bedroom_motion_off
      - service: light.turn_off
        entity_id: light.bathroom_vanity
      - service: light.turn_off
        entity_id: light.bathroom
      - service: switch.turn_off
        entity_id: switch.wemo_master_bath_fan
      - service: switch.turn_off
        entity_id: switch.wemo_master_bath_heater    

  getting_dressed_on:
    sequence:
      - delay: '00:00:01'
      - service: automation.turn_off
        entity_id: automation.motion_bathroom_home_mode_off
      - service: automation.turn_off
        entity_id: automation.motion_bathroom_sleep_off
      - service: automation.turn_off
        entity_id: automation.motion_master_bedroom_motion_off
      - service: light.turn_on
        data:
          entity_id: light.bathroom_vanity
          color_temp: 154
          brightness: 255
      - service: light.turn_on
        data:
          entity_id: light.bathroom
          color_temp: 154
          brightness: 255
      - service: light.turn_on
        data:
          entity_id: light.master_table_lamps
          color_temp: 154
          brightness: 255
      - service: light.turn_on
        data:
          entity_id: light.light_bulb_2


  getting_dressed_off:
    sequence:
      - delay: '00:00:01'
      - service: automation.turn_on
        entity_id: automation.motion_bathroom_home_mode_off
      - service: automation.turn_on
        entity_id: automation.motion_bathroom_sleep_off
      - service: automation.turn_on
        entity_id: automation.motion_master_bedroom_motion_off
      - service: light.turn_off
        entity_id: light.bathroom_vanity
      - service: light.turn_off
        entity_id: light.bathroom

  # shower_time_warmup_on:
  #   sequence:
  #     - delay: '00:00:01'
  #     - service: switch.turn_on
  #       entity_id: switch.wemo_master_bath_heater
  #
  # shower_time_warmup_off:
  #   sequence:
  #     - delay: '00:00:01'
  #     - service: switch.turn_off
  #       entity_id: switch.wemo_master_bath_heater

switch:
  - platform: template
    switches:
      shower_time:
        value_template: "{{ is_state('light.bathroom_vanity', 'on') }}"
        turn_on:
          - service: script.turn_on
            data:
              entity_id: script.bath_time_on
        turn_off:
          - service: script.turn_on
            data:
              entity_id: script.bath_time_off
  - platform: template
    switches:
      getting_dressed:
        value_template: "{{ is_state('light.bathroom_vanity', 'on') }}"
        turn_on:
          - service: script.turn_on
            data:
              entity_id: script.getting_dressed_on
        turn_off:
          - service: script.turn_on
            data:
              entity_id: script.getting_dressed_off
  # - platform: template
  #   switches:
  #     shower_time_warmup:
  #       value_template: "{{ is_state('switch.wemo_master_bath_heater', 'on') }}"
  #       turn_on:
  #         - service: script.turn_on
  #           data:
  #             entity_id: script.shower_time_warmup_on
  #       turn_off:
  #         - service: script.turn_on
  #           data:
  #             entity_id: script.shower_time_warmup_off
