homeassistant:
  customize:
    sensor.speedtest_download:
      entity_picture: /local/speedtest.png
    sensor.speedtest_upload:
      entity_picture: /local/speedtest.png
    sensor.speedtest_ping:
      entity_picture: /local/ping.jpg
    sensor.download_speed_mean:
      friendly_name: 'Speedtest Download Average'
      icon: mdi:speedometer
    sensor.upload_speed_mean:
      friendly_name: 'Speedtest Upload Average'
      icon: mdi:speedometer
    sensor.ping_time_mean:
      friendly_name: 'Speedtest Ping Average'
      icon: mdi:clock-fast
    camera.living_room_camera:
      friendly_name: Living Room Camera
    sensor.shed_camera:
      friendly_name: Shed Camera
      entity_picture: /local/ipcameraicon.jpeg
    sensor.driveway_camera:
      friendly_name: Driveway Camera
      entity_picture: /local/ipcameraicon.jpeg
    sensor.number12_camera:
      friendly_name: Number12 Camera
      entity_picture: /local/ipcameraicon.jpeg
    sensor.swamp_camera:
      friendly_name: Swamp Camera
      entity_picture: /local/ipcameraicon.jpeg
    sensor.frontdoor_camera:
      friendly_name: Front Door Camera
      entity_picture: /local/ipcameraicon.jpeg
    sensor.backdoor_camera:
      friendly_name: Back Door Camera
      entity_picture: /local/ipcameraicon.jpeg
    sensor.asus_router:
      friendly_name: Asus Merlin
      entity_picture: /local/AsusMerlin.jpeg
    sensor.cisco_router:
      friendly_name: Cisco Router
      entity_picture: /local/cisco54.jpeg
    sensor.netgear_router:
      friendly_name: Netgear Router
      entity_picture: /local/netgear.jpeg
    sensor.switch2:
      friendly_name: Switch 2
      entity_picture: /local/8PortSwitch.jpeg
    sensor.switch1:
      friendly_name: Switch 1
      entity_picture: /local/8PortSwitch.jpeg
    sensor.media_nas:
      friendly_name: Media Nas
      entity_picture: /local/Worldbook.jpeg
    sensor.network_nas:
      friendly_name: Network Nas
      entity_picture: /local/Worldbook.jpeg
    sensor.blue_iris_workstation:
      friendly_name: Blue Iris Server
      entity_picture: /local/workstation.jpeg
    sensor.network_workstation:
      friendly_name: Network Workstation
      entity_picture: /local/workstation.jpeg
    sensor.harmony_hub:
      friendly_name: Harmony Hub
      icon: mdi:black-mesa
    sensor.hue_hub:
      friendly_name: Hue Hub
      icon: mdi:black-mesa
    sensor.wink_hub:
      friendly_name: Wink Hub
      icon: mdi:black-mesa
    sensor.wink_fan_gang:
      friendly_name: Fan Connection
      icon: mdi:nfc
    sensor.wink_fan_master_gang:
      friendly_name: Master Fan Connection
      icon: mdi:nfc
    sensor.myipopendnscom:
      friendly_name: Wan Ip
      icon: mdi:wan
    sensor.esp_kitchen_blinds:
      friendly_name: Kitchen Blinds Controller
      entity_picture: /local/nodemcu.jpeg
    sensor.esp_kitchen_sink_blinds:
      friendly_name: Kitchen Sink Blinds Controller
      entity_picture: /local/nodemcu.jpeg
    sensor.esp_lv_room_dawn_blinds:
      friendly_name: Dawns Blinds
      entity_picture: /local/nodemcu.jpeg
    sensor.esp_lv_room_herbs_blinds:
      friendly_name: Herbs Blinds
      entity_picture: /local/nodemcu.jpeg
    sensor.esp_lv_room_front_blinds:
      friendly_name: Front Blinds
      entity_picture: /local/nodemcu.jpeg
    sensor.esp_kitchen_led:
      friendly_name: Kitchen Led Controller
      entity_picture: /local/nodemcu.jpeg
    sensor.esp_smallfishtank_led:
      friendly_name: Small Fish Tank Led Controller
      entity_picture: /local/nodemcu.jpeg
    sensor.esp_dawns_controller:
      friendly_name: Dawns Contoller
      entity_picture: /local/nodemcu.jpeg
    sensor.gabbies_laptop:
      friendly_name: Gabbies Laptop
      icon: mdi:laptop
    sensor.dashboard_tablet_lv:
      friendly_name: Dashboard Tablet
      icon: mdi:tablet-android
    sensor.dashboard_tablet_bedroom:
      friendly_name: Dashboard Tablet Bedroom
      icon: mdi:tablet-android
    sensor.clients:
      friendly_name: Clients Tracked
      icon: mdi:network
group:
  clients_online_card:
    name: Clients Online
    entities:
      - sensor.clients

  hubs_card:
   name: Hub's & Bridges
   entities:
     - sensor.harmony_hub
     - sensor.hue_hub
     - sensor.wink_hub

  cameras_status_card:
    name: Cameras
    entities:
     - sensor.number12_camera
     - sensor.driveway_camera
     - sensor.shed_camera
     - sensor.backdoor_camera
     - sensor.frontdoor_camera
     - sensor.swamp_camera

  NetworkDrives_status_card:
   name: Nas Drives
   entities:
     - sensor.media_nas
     - sensor.network_nas

  NetworkNmap_status_card:
   name: Network Equipment
   entities:
     - sensor.asus_router
     - sensor.cisco_router
     - sensor.netgear_router
     - sensor.switch1
     - sensor.switch2

  esp_devices_card:
   name: Esp Controller's
   entities:
     - sensor.esp_kitchen_blinds
     - sensor.blinds_controller_wifi_signal
     - sensor.esp_kitchen_sink_blinds
     - sensor.sink_blinds_controller_wifi_signal
     - sensor.esp_kitchen_led
     - sensor.esp_smallfishtank_led
     - sensor.esp_dawns_controller
     - sensor.dawns_controller_wifi_signal
     - sensor.esp_lv_room_dawn_blinds
     - sensor.dawns_blinds_controller_wifi_signal
     - sensor.esp_lv_room_herbs_blinds
     - sensor.herb_blinds_controller_wifi_signal
     - sensor.esp_lv_room_front_blinds
     - sensor.front_blinds_controller_wifi_signal

  etc_devices_card:
   name: Tracked Network Devices
   entities:
     - sensor.gabbies_laptop
     - sensor.dashboard_tablet_lv
     - sensor.dashboard_tablet_bedroom

sensor:
  ############## Public Ip
  - platform: dnsip

######## Equipment ########
  - platform: speedtest
    minute: 30
    hour:
      - 0
      - 6
      - 12
      - 18
    monitored_conditions:
      - ping
      - download
      - upload

##### show devices as online instead of home   ############################
  - platform: template
    sensors:
      shed_camera:
        value_template: '{% if is_state("binary_sensor.shed_camera", "on") %}Online{% else %}Offline{% endif %}'
  - platform: template
    sensors:
      driveway_camera:
        value_template: '{% if is_state("device_tracker.drivewaycamvasiley", "home") %}Online{% else %}Offline{% endif %}'
  - platform: template
    sensors:
      number12_camera:
        value_template: '{% if is_state("device_tracker.number12vasiley", "home") %}Online{% else %}Offline{% endif %}'
  - platform: template
    sensors:
      swamp_camera:
        value_template: '{% if is_state("device_tracker.shedvasiley", "home") %}Online{% else %}Offline{% endif %}'
  - platform: template
    sensors:
      frontdoor_camera:
        value_template: '{% if is_state("device_tracker.frontdoorvasiley", "home") %}Online{% else %}Offline{% endif %}'
  - platform: template
    sensors:
      backdoor_camera:
        value_template: '{% if is_state("device_tracker.backdoorvasiley", "home") %}Online{% else %}Offline{% endif %}'
  - platform: template
    sensors:
      asus_router:
        value_template: '{% if is_state("device_tracker.routerasuscom", "home") %}Online{% else %}Offline{% endif %}'
  - platform: template
    sensors:
      cisco_router:
        value_template: '{% if is_state("device_tracker.pan_shedvasiley", "home") %}Online{% else %}Offline{% endif %}'
  - platform: template
    sensors:
      switch2:
        value_template: '{% if is_state("device_tracker.blueirispcvasiley", "home") %}Online{% else %}Offline{% endif %}'
  - platform: template
    sensors:
      switch1:
        value_template: '{% if is_state("device_tracker.switch1vasiley", "home") %}Online{% else %}Offline{% endif %}'
  - platform: template
    sensors:
      media_nas:
        value_template: '{% if is_state("device_tracker.medianasvasiley", "home") %}Online{% else %}Offline{% endif %}'
  - platform: template
    sensors:
      network_nas:
        value_template: '{% if is_state("device_tracker.nasnetworkvasiley", "home") %}Online{% else %}Offline{% endif %}'
  - platform: template
    sensors:
      blue_iris_workstation:
        value_template: '{% if is_state("device_tracker.blueiris2vasiley", "home") %}Online{% else %}Offline{% endif %}'
  - platform: template
    sensors:
      network_workstation:
        value_template: '{% if is_state("device_tracker.networkpcvasiley", "home") %}Online{% else %}Offline{% endif %}'
  - platform: template
    sensors:
      wink_fan_gang:
        value_template: '{% if is_state("binary_sensor.gang", "on") %}Online{% else %}Offline{% endif %}'
  - platform: template
    sensors:
      wink_fan_master_gang:
        value_template: '{% if is_state("binary_sensor.gang_1", "on") %}Online{% else %}Offline{% endif %}'
  - platform: template
    sensors:
      harmony_hub:
        value_template: '{% if is_state("device_tracker.harmonyhubvasiley", "home") %}Online{% else %}Offline{% endif %}'
  - platform: template
    sensors:
      hue_hub:
        value_template: '{% if is_state("device_tracker.huebridge", "home") %}Online{% else %}Offline{% endif %}'
  - platform: template
    sensors:
      wink_hub:
        value_template: '{% if is_state("binary_sensor.wink_hub_2", "on") %}Online{% else %}Offline{% endif %}'
  - platform: template
    sensors:
      esp_kitchen_blinds:
        value_template: '{% if is_state("device_tracker.5ccf7fb19112", "home") %}Online{% else %}Offline{% endif %}'
  - platform: template
    sensors:
      esp_kitchen_sink_blinds:
        value_template: '{% if is_state("device_tracker.2c3ae805f66b", "home") %}Online{% else %}Offline{% endif %}'
  - platform: template
    sensors:
      esp_lv_room_dawn_blinds:
        value_template: '{% if is_state("device_tracker.60019473e472", "home") %}Online{% else %}Offline{% endif %}'
  - platform: template
    sensors:
      esp_lv_room_herbs_blinds:
        value_template: '{% if is_state("device_tracker.6001947550b3", "home") %}Online{% else %}Offline{% endif %}'
  - platform: template
    sensors:
      esp_lv_room_front_blinds:
        value_template: '{% if is_state("device_tracker.60019473e681", "home") %}Online{% else %}Offline{% endif %}'
  - platform: template
    sensors:
      esp_kitchen_led:
        value_template: '{% if is_state("device_tracker.600194316a56", "home") %}Online{% else %}Offline{% endif %}'
  - platform: template
    sensors:
      esp_smallfishtank_led:
        value_template: '{% if is_state("device_tracker.600194316502", "home") %}Online{% else %}Offline{% endif %}'
  - platform: template
    sensors:
      esp_dawns_controller:
        value_template: '{% if is_state("device_tracker.5ccf7fb565ff", "home") %}Online{% else %}Offline{% endif %}'
  - platform: template
    sensors:
      gabbies_laptop:
        value_template: '{% if is_state("device_tracker.f82819c42847", "home") %}Online{% else %}Offline{% endif %}'
  - platform: template
    sensors:
      dashboard_tablet_lv:
        value_template: '{% if is_state("device_tracker.androida64e0f70e33eb022", "home") %}Online{% else %}Offline{% endif %}'
  - platform: template
    sensors:
      dashboard_tablet_bedroom:
        value_template: '{% if is_state("device_tracker.4ca56d68487b", "home") %}Online{% else %}Offline{% endif %}'
  - platform: template
    sensors:
      netgear_router:
        value_template: '{% if is_state("device_tracker.e8fcaf8a04de", "home") %}Online{% else %}Offline{% endif %}'
  - platform: template
    sensors:
      clients:
        value_template: >-
            {%- for d in states.device_tracker if d.state == 'home' -%}
            {{- loop.length if loop.first -}}
            {%- endfor -%}

device_tracker:
  - platform: nmap_tracker
    home_interval: 60
    hosts: 192.168.1.1-255
    consider_home: 180
    interval_seconds: 120
    exclude:
      - 192.168.1.153

  - platform: owntracks
    max_gps_accuracy: 200

binary_sensor:
  - platform: ping
    host: 192.168.1.90
    name: Shed Camera

#### Notify if device goes offline

automation:
  - alias: Notify Device Status
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id:
          - sensor.wink_fan_gang
          - sensor.wink_fan_master_gang
          - sensor.network_workstation
          - sensor.blue_iris_workstation
          - sensor.network_nas
          - sensor.media_nas
          - sensor.switch1
          - sensor.switch2
          - sensor.cisco_router
          - sensor.asus_router
          - sensor.backdoor_camera
          - sensor.frontdoor_camera
          - sensor.shed_camera
          - sensor.driveway_camera
          - sensor.number12_camera
          - sensor.swamp_camera
          - sensor.harmony_hub
          - sensor.hue_hub
          - sensor.wink_hub
          - sensor.esp_kitchen_blinds
          - sensor.esp_kitchen_sink_blinds
          - sensor.esp_kitchen_led1
          - sensor.esp_smallfishtank_led
          - sensor.gabbies_laptop
          - sensor.dashboard_tablet_bedroom
          - sensor.netgear_router
          - sensor.esp_lv_room_dawn_blinds
          - sensor.esp_lv_room_herbs_blinds
          - sensor.esp_lv_room_front_blinds

#        for: '00:00:01'
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{% if trigger.from_state and trigger.to_state %} True {% else %} False {% endif %}"
        - condition: state
          entity_id: input_boolean.boolean_home
          state: 'on'
    action:
      - service: tts.google_say
        data_template:
          entity_id: media_player.ha_speaker
          message: >
            {% if trigger.to_state.state | lower == "offline" %}
              {{ trigger.to_state.attributes.friendly_name }} has gone offline!
            {% else %}
              {{ trigger.to_state.attributes.friendly_name }} has come online!
            {% endif %}
