##### I use this for a group view with entities are in different packages....If in one package group
##### view is in there
homeassistant:
  customize:

    package.node_anchors:
      customize: &customize
        package: 'room_room_groups'

group:
 livingroom_card:
    control: hidden
    name: Living Room
    entities:
     - light.lamps
     - light.herbs_lamp
     - light.dawns_lamp
     - light.door_lamp
     - fan.living_room_fan
     - script.living_room_fan_auto
     - sensor.fan_speed
     - binary_sensor.gang
     - script.refresh_wink
     - automation.fan_low_with_hvac_automation
     - automation.fan_medium_with_hvac_automation
     - automation.reenable_fan_automation
     - switch.fan_override
     - automation.evening_time_turn_on
     - light.light_bulb
     - automation.evening_time
     - script.evening_time
     - script.movie_time
     - automation.back_to_white_after_motion
     - automation.back_to_yellow_dim_after_motion
     - script.nap_time
     - script.front_cam_dashboard
     - script.vas_dashboard
     - switch.dawns_scent

 master_bedroom_card:
    control: hidden
    name: Master Bedroom
    entities:
     - light.dawns_bedside_lamp
     - light.herbs_bedside_lamp
     - light.master_table_lamps
     - light.light_bulb_2
     - fan.master_bedroom_fan
     - script.master_fan_auto
     - sensor.fan_speed_master
     - binary_sensor.gang_1
     - binary_sensor.master_motion
     - binary_sensor.bedroom_motion
     - sensor.master_bedroom_temperature
     - sensor.motion_sensor_master_battery
     - sensor.motion_sensor_master_lux
     - sensor.bedroom_wallpanel_battery
     - sensor.bedroom_wallpanel_brightness
     - automation.motion_master_bedroom_homemode
     - automation.motion_master_bedroom_evening_and_movie_time_on
     - automation.motion_master_bedroom_motion_off
     - binary_sensor.master_bedroom_occupancy
     - switch.fan_on
     - switch.dawn_day
     - switch.dawn_night
     - automation.candle_on_during_home_mode
     - automation.candle_off_when_not_home_mode
     - automation.fan_on_during_sleep_mode
     - automation.fan_off_when_home_mode

 master_bath_card:
    control: hidden
    name: Master Bath
    entities:
     - light.bathroom_vanity
     - light.bathroom
     - switch.master_bath
     - binary_sensor.bathroom_motion
     - sensor.bathroom_temperature
     - sensor.motion_sensor_bathroom_battery
     - sensor.master_bathroom_dimmer_state
     - sensor.master_bathroom_dimmer_last_update
     - sensor.master_bathroom_dimmer_battery
     - script.shower_time_on
     - script.shower_time_off
     - switch.shower_time
     - automation.master_bath_light_left_on
     - automation.master_bath_shower_time_off
     - automation.master_bath_shower_time_on
     - automation.motion_bathroom_home_mode_off
     - automation.motion_bathroom_home_mode_on
     - automation.motion_bathroom_evening_mode_on
     - automation.motion_bathroom_sleep_off
     - automation.motion_bathroom_sleep_on

 kids_bath_card:
    control: hidden
    name: Kids Bath
    entities:
     - light.kids_bathroom
     - light.kids_bathroom_vanity
     - switch.kids_bathroom_scent
     - binary_sensor.kids_bathroom_motion
     - sensor.kids_bathroom_temperature
     - sensor.kids_bathroom_motion_sensor_lux
     - sensor.motion_sensor_kids_bathroom_battery
     - sensor.kids_bathroom_dimmer_state
     - sensor.kids_bathroom_dimmer_last_update
     - sensor.kids_bathroom_dimmer_battery
     - script.kids_shower_time_on
     - script.kids_shower_time_off
     - switch.kids_shower_time
     - automation.kids_bath_light_left_on
     - automation.kids_bath_shower_time_off
     - automation.kids_bath_shower_time_on
     - automation.motion_kids_bathroom_home_mode_off
     - automation.motion_kids_bathroom_home_mode_on
     - automation.motion_kids_bathroom_evening_mode_on
     - automation.motion_kids_bathroom_sleep_off
     - automation.motion_kids_bathroom_sleep_on

 carport_lights_card:
    control: hidden
    name: Carport
    entities:
      - light.carport
      - light.front_steps
      - light.rear_steps
      - automation.porch_lights_on
      - automation.porch_lights_off
      - automation.front_carport_bright_and_white_on_motion
      - automation.front_back_to_yellow_dim_after_Motion
      - script.front_bright_outside
      - script.front_normal_outside

 kitchen_card:
   control: hidden
   name: Kitchen
   entities:
      - light.kitchen_under_cabinet
      - light.kitchen
      - light.kitchen_table
      - input_number.led_animation_speed
      - light.kitchen_white
      - script.led_white
      - script.led_yellow
      - script.led_off
      - automation.kitchen_lights_off_with_dimmer
      - automation.kitchen_lights_on_white_with_dimmer
      - automation.led_animation_speed
      - automation.kitchen_leds_low_light_on
      - automation.kitchen_leds_low_light_off
      - automation.motion_kitchen_main_light_on
      - automation.motion_kitchen_off
      - sensor.Kitchen_dimmer_test
      - sensor.motion_sensor_kitchen_lux
      - input_select.kitchen_blinds_status
      - sensor.kitchen_blinds_state
      - script.blinds_closed
      - script.blinds_halfway
      - script.blinds_open

 laundry_room_card:
   control: hidden
   name: Laundry Room
   entities:
      - light.laundry_room
      - binary_sensor.laundry_room_motion
      - sensor.motion_sensor_laundry_battery
      - sensor.laundry_temperature
      - sensor.motion_sensor_laundry_lux
      - automation.laundry_motion_homeMode
      - automation.laundry_motion_not_homeMode
      - automation.laundry_motion_off
      - switch.wemo_washing_machine
      - sensor.washing_machine_watts
      - sensor.washing_machine_power_up
      - sensor.washing_machine_power_down
      - input_boolean.stopwatch
      - input_boolean.dummy
      - input_boolean.washer_switch
      - sensor.stopwatch
      - sensor.washer_status
      - automation.washer_start
      - automation.washer_done
      - automation.stopwatch_start
      - automation.stopwatch_stop
      - automation.stopwatch_update

 master_hallway_card:
   control: hidden
   name: Master Hallway
   entities:
     - light.master_hallway
     - sensor.motion_sensor_hallway_battery
     - binary_sensor.hallway_motion
     - sensor.hallway_temperature
     - sensor.master_hallway_motion_sensor_lux
     - automation.motion_master_hallway_motion_on
     - automation.motion_master_hallway_motion_off

 kids_hallway_card:
   control: hidden
   name: Kids Hallway
   entities:
     - light.kids_hallway
     - sensor.motion_sensor_hallway_battery
     - binary_sensor.kids_hallway_motion
     - sensor.kids_hallway_temperature
     - sensor.kids_hallway_motion_sensor_lux
     - automation.motion_kids_hallway_motion_on
     - automation.motion_kids_hallway_motion_off

 ruths_room_card:
   control: hidden
   name: Ruths Room
   entities:
     - sensor.ruths_room_temperature
     - binary_sensor.ruths_room_occupancy
     - switch.ruths_room_scent
     - switch.driveway_camera
     - script.driveway_cam_powercycle
     - automation.reboot_driveway_camera
