homeassistant:
  customize:
    sensor.pws_alerts:
      icon: mdi:alert-outline
      friendly_name: Alerts
    sensor.pws_feelslike_f:
      friendly_name: Feels Like
    sensor.pws_temp_f:
      friendly_name: Temperature
    sensor.pws_observation_time:
      icon: mdi:timer-sand
      friendly_name: Observation Time
    sensor.pws_weather:
      friendly_name: Conditions
    sensor.pws_wind_dir:
      icon: mdi:compass-outline
      friendly_name: Direction
    sensor.pws_wind_mph:
      icon: mdi:speedometer
      friendly_name: Wind Speed
    sensor.pws_wind_gust_mph:
      icon: mdi:speedometer
      friendly_name: Gust
    sensor.pws_precip_today_in:
      icon: mdi:weather-pouring
      friendly_name: Rain Today
    sensor.pws_precip_1hr_in:
      icon: mdi:weather-pouring
      friendly_name: Inch Per Hour
    sensor.pws_relative_humidity:
      entity_picture: /local/drop.png
      friendly_name: Humidity
    sensor.pws_visibility_mi:
      friendly_name: Visibility
    sensor.dark_sky_daily_summary:
      friendly_name: Daily
    sensor.dark_sky_hourly_summary:
      friendly_name: Hourly
    sensor.dark_sky_minutely_summary:
      friendly_name: To the Minute
    sensor.yw_day1_condition:
      friendly_name: Tomorrows Weather
    sensor.yw_day1_temperature_max:
      friendly_name: Tomorrows High
    sensor.yw_day1_temperature_min:
      friendly_name: Tomorrows Low
    sensor.yw_day2_condition:
      friendly_name: 2nd day Weather Conditions
    sensor.yw_day2_temperature_max:
      friendly_name: 2nd day High
    sensor.yw_day2_temperature_min:
      friendly_name: 2nd day Low
    sensor.yw_day3_condition:
      friendly_name: 3rd day Weather Conditions
    sensor.yw_day3_temperature_max:
      friendly_name: 3rd day High
    sensor.yw_day3_temperature_min:
      friendly_name: 3rd day Low

group:
  ForecastWeather_card:
   name: Predication
   entities:
     - sensor.dark_sky_summary
     - sensor.dark_sky_daily_summary
     - sensor.dark_sky_hourly_summary
     - sensor.dark_sky_minutely_summary
     - sensor.dark_sky_daily_high_temperature
     - sensor.dark_sky_daily_low_temperature
     - sensor.dark_sky_precip_probability
     - sensor.dark_sky_nearest_storm_bearing
     - sensor.dark_sky_nearest_storm_distance

  daily_forecast_card:
    name: Daily Forecast
    entities:
      - sensor.pws_weather_1d
      - sensor.pws_weather_1n
      - sensor.pws_weather_2d
      - sensor.pws_weather_2n
      - sensor.pws_weather_3d
      - sensor.pws_weather_3n
      - sensor.pws_weather_4d
      - sensor.pws_weather_4n

  Conditions_card:
   name: Current Weather
   entities:
     - sensor.pws_observation_time
     - sensor.pws_alerts
     - sensor.pws_weather
     - sensor.pws_Temp_f
     - sensor.pws_feelslike_f
     - sensor.pws_wind_dir
     - sensor.pws_wind_mph
     - sensor.pws_wind_gust_mph
     - sensor.pws_relative_humidity
     - sensor.pws_precip_1hr_in
     - sensor.pws_precip_today_in
     - sensor.pws_visibility_mi
     - sun.sun

  animated_radar_card:
   name: Animated Radar
   entities:
     - camera.Radar_Animated

  still_image_radar_card:
   name: Still Radar
   entities:
     - camera.radar

camera:
  - platform: generic
    still_image_url: !secret radar
    name: Radar

  - platform: generic
    still_image_url: 'http://images.intellicast.com/WxImages/RadarLoop/msy_None_anim.gif'
    name: Radar Animated

weather:
  # - platform: darksky
  #   api_key: !secret darksky_api
  - platform: yweather

sensor:
  - platform: wunderground
    api_key: !secret wunderground_api
    monitored_conditions:
      - alerts
      - feelslike_f
      - observation_time
      - precip_1hr_in
      - precip_today_in
      - relative_humidity
      - temp_f
      - visibility_mi
      - weather
      - wind_dir
      - wind_gust_mph
      - wind_mph
      - weather_1d
      - weather_1n
      - weather_2d
      - weather_2n
      - weather_3d
      - weather_3n
      - weather_4d
      - weather_4n

  - platform: darksky
    api_key: !secret darksky_api

    monitored_conditions:
      - summary
      - nearest_storm_distance
      - nearest_storm_bearing
      - precip_probability
      - minutely_summary
      - hourly_summary
      - daily_summary
      - temperature_max
      - temperature_min
      - temperature
      - humidity
      - precip_probability
      - precip_intensity
      - wind_speed
      - pressure
      - wind_bearing
      - apparent_temperature
      - icon
